insert into public.inventory_items (
  id,
  alias,
  nombre,
  ubicacion,
  categoria,
  categoria_principal,
  subcategoria,
  contenido,
  notas,
  cantidad_actual,
  cantidad_minima,
  unidad,
  thumbnail_url,
  nfc_mode
)
values
  ('CP-PASTA-DENTAL-001','CP-0001','Pasta dental','Bano principal','aseo_personal','casa','aseo_personal','[]'::jsonb,null,0,1,'unidad','https://loremflickr.com/800/500/toothpaste','none'),
  ('CP-CEPILLO-DENTAL-001','CP-0002','Cepillo dental','Bano principal','aseo_personal','casa','aseo_personal','[]'::jsonb,null,0,1,'unidad','https://loremflickr.com/800/500/toothbrush','none'),
  ('CP-ENJUAGUE-BUCAL-001','CP-0003','Enjuague bucal','Bano principal','aseo_personal','casa','aseo_personal','[]'::jsonb,null,0,1,'botella','https://loremflickr.com/800/500/mouthwash','none'),
  ('CP-DESODORANTE-001','CP-0004','Desodorante','Bano principal','aseo_personal','casa','aseo_personal','[]'::jsonb,null,0,1,'unidad','https://loremflickr.com/800/500/deodorant','none'),
  ('CP-JABON-001','CP-0005','Jabon','Bano principal','aseo_personal','casa','aseo_personal','[]'::jsonb,null,0,1,'unidad','https://loremflickr.com/800/500/soap','none'),
  ('CP-SHAMPOO-001','CP-0006','Shampoo','Bano principal','aseo_personal','casa','aseo_personal','[]'::jsonb,null,0,1,'botella','https://loremflickr.com/800/500/shampoo','none'),
  ('CP-CONDITIONER-001','CP-0007','Conditioner','Bano principal','aseo_personal','casa','aseo_personal','[]'::jsonb,null,0,1,'botella','https://loremflickr.com/800/500/conditioner','none'),
  ('CP-PAPEL-HIGIENICO-001','CP-0008','Papel higienico','Bano principal','aseo_personal','casa','aseo_personal','[]'::jsonb,null,0,1,'paquete','https://loremflickr.com/800/500/toilet-paper','none'),
  ('CP-TOALLAS-SANITARIAS-001','CP-0009','Toallas sanitarias','Bano principal','aseo_personal','casa','aseo_personal','[]'::jsonb,null,0,1,'paquete','https://loremflickr.com/800/500/sanitary-pad','none'),
  ('CP-RASURADORAS-001','CP-0010','Rasuradoras','Bano principal','aseo_personal','casa','aseo_personal','[]'::jsonb,null,0,1,'paquete','https://loremflickr.com/800/500/razor','none'),
  ('CP-CREMA-CORPORAL-001','CP-0011','Crema corporal','Bano principal','aseo_personal','casa','aseo_personal','[]'::jsonb,null,0,1,'botella','https://loremflickr.com/800/500/body-lotion','none'),
  ('CP-TALCO-001','CP-0012','Talco','Bano principal','aseo_personal','casa','aseo_personal','[]'::jsonb,null,0,1,'unidad','https://loremflickr.com/800/500/talcum-powder','none'),
  ('CP-HILO-DENTAL-001','CP-0013','Hilo dental','Bano principal','aseo_personal','casa','aseo_personal','[]'::jsonb,null,0,1,'unidad','https://loremflickr.com/800/500/dental-floss','none'),
  ('CP-HISOPOS-001','CP-0014','Hisopos','Bano principal','aseo_personal','casa','aseo_personal','[]'::jsonb,null,0,1,'paquete','https://loremflickr.com/800/500/cotton-swab','none'),
  ('CP-TOALLITAS-HUMEDAS-001','CP-0015','Toallitas humedas','Bano principal','aseo_personal','casa','aseo_personal','[]'::jsonb,null,0,1,'paquete','https://loremflickr.com/800/500/wet-wipes','none'),

  ('CC-DETERGENTE-001','CC-0001','Detergente','Cuarto de limpieza','aseo_casa','casa','aseo_casa','[]'::jsonb,null,0,1,'botella','https://loremflickr.com/800/500/detergent','none'),
  ('CC-CLORO-001','CC-0002','Cloro','Cuarto de limpieza','aseo_casa','casa','aseo_casa','[]'::jsonb,null,0,1,'botella','https://loremflickr.com/800/500/bleach','none'),
  ('CC-DESINFECTANTE-001','CC-0003','Desinfectante','Cuarto de limpieza','aseo_casa','casa','aseo_casa','[]'::jsonb,null,0,1,'botella','https://loremflickr.com/800/500/disinfectant','none'),
  ('CC-JABON-FREGAR-001','CC-0004','Jabon de fregar','Cuarto de limpieza','aseo_casa','casa','aseo_casa','[]'::jsonb,null,0,1,'botella','https://loremflickr.com/800/500/dish-soap','none'),
  ('CC-ESPONJAS-001','CC-0005','Esponjas','Cuarto de limpieza','aseo_casa','casa','aseo_casa','[]'::jsonb,null,0,1,'paquete','https://loremflickr.com/800/500/sponge','none'),
  ('CC-BOLSAS-BASURA-001','CC-0006','Bolsas de basura','Cuarto de limpieza','aseo_casa','casa','aseo_casa','[]'::jsonb,null,0,1,'paquete','https://loremflickr.com/800/500/garbage-bag','none'),
  ('CC-LIMPIADOR-PISO-001','CC-0007','Limpiador de piso','Cuarto de limpieza','aseo_casa','casa','aseo_casa','[]'::jsonb,null,0,1,'botella','https://loremflickr.com/800/500/floor-cleaner','none'),
  ('CC-LIMPIADOR-BANO-001','CC-0008','Limpiador de bano','Cuarto de limpieza','aseo_casa','casa','aseo_casa','[]'::jsonb,null,0,1,'botella','https://loremflickr.com/800/500/bathroom-cleaner','none'),
  ('CC-LIMPIADOR-CRISTAL-001','CC-0009','Limpiador de cristal','Cuarto de limpieza','aseo_casa','casa','aseo_casa','[]'::jsonb,null,0,1,'botella','https://loremflickr.com/800/500/glass-cleaner','none'),
  ('CC-TOALLAS-PAPEL-001','CC-0010','Toallas de papel','Cuarto de limpieza','aseo_casa','casa','aseo_casa','[]'::jsonb,null,0,1,'paquete','https://loremflickr.com/800/500/paper-towels','none'),
  ('CC-SUAVIZADOR-001','CC-0011','Suavizador','Cuarto de limpieza','aseo_casa','casa','aseo_casa','[]'::jsonb,null,0,1,'botella','https://loremflickr.com/800/500/fabric-softener','none'),
  ('CC-REMOVEDOR-GRASA-001','CC-0012','Removedor de grasa','Cuarto de limpieza','aseo_casa','casa','aseo_casa','[]'::jsonb,null,0,1,'botella','https://loremflickr.com/800/500/degreaser','none'),
  ('CC-GUANTES-LIMPIEZA-001','CC-0013','Guantes de limpieza','Cuarto de limpieza','aseo_casa','casa','aseo_casa','[]'::jsonb,null,0,1,'par','https://loremflickr.com/800/500/cleaning-gloves','none'),
  ('CC-AMBIENTADOR-001','CC-0014','Ambientador','Cuarto de limpieza','aseo_casa','casa','aseo_casa','[]'::jsonb,null,0,1,'unidad','https://loremflickr.com/800/500/air-freshener','none'),
  ('CC-CEPILLO-INODORO-001','CC-0015','Cepillo de inodoro','Cuarto de limpieza','aseo_casa','casa','aseo_casa','[]'::jsonb,null,0,1,'unidad','https://loremflickr.com/800/500/toilet-brush','none'),

  ('CM-BOMBILLAS-001','CM-0001','Bombillas','Gabinete de repuestos','mejoras_casa','casa','mejoras_casa','[]'::jsonb,null,0,1,'paquete','https://loremflickr.com/800/500/light-bulb','none'),
  ('CM-EXTENSIONES-001','CM-0002','Extensiones','Gabinete de repuestos','mejoras_casa','casa','mejoras_casa','[]'::jsonb,null,0,1,'unidad','https://loremflickr.com/800/500/extension-cord','none'),
  ('CM-BATERIAS-AA-001','CM-0003','Baterias AA','Gabinete de repuestos','mejoras_casa','casa','mejoras_casa','[]'::jsonb,null,0,1,'paquete','https://loremflickr.com/800/500/aa-battery','none'),
  ('CM-BATERIAS-AAA-001','CM-0004','Baterias AAA','Gabinete de repuestos','mejoras_casa','casa','mejoras_casa','[]'::jsonb,null,0,1,'paquete','https://loremflickr.com/800/500/aaa-battery','none'),
  ('CM-TAPE-ELECTRICO-001','CM-0005','Tape electrico','Gabinete de repuestos','mejoras_casa','casa','mejoras_casa','[]'::jsonb,null,0,1,'unidad','https://loremflickr.com/800/500/electrical-tape','none'),
  ('CM-TORNILLOS-SURTIDOS-001','CM-0006','Tornillos surtidos','Gabinete de repuestos','mejoras_casa','casa','mejoras_casa','[]'::jsonb,null,0,1,'caja','https://loremflickr.com/800/500/screws','none'),
  ('CM-CLAVOS-001','CM-0007','Clavos','Gabinete de repuestos','mejoras_casa','casa','mejoras_casa','[]'::jsonb,null,0,1,'caja','https://loremflickr.com/800/500/nails','none'),
  ('CM-ADAPTADORES-001','CM-0008','Adaptadores','Gabinete de repuestos','mejoras_casa','casa','mejoras_casa','[]'::jsonb,null,0,1,'unidad','https://loremflickr.com/800/500/power-adapter','none'),
  ('CM-REGLETA-001','CM-0009','Regleta','Gabinete de repuestos','mejoras_casa','casa','mejoras_casa','[]'::jsonb,null,0,1,'unidad','https://loremflickr.com/800/500/power-strip','none'),
  ('CM-LINTERNA-001','CM-0010','Linterna','Gabinete de repuestos','mejoras_casa','casa','mejoras_casa','[]'::jsonb,null,0,1,'unidad','https://loremflickr.com/800/500/flashlight','none'),
  ('CM-FUSIBLES-001','CM-0011','Fusibles','Gabinete de repuestos','mejoras_casa','casa','mejoras_casa','[]'::jsonb,null,0,1,'paquete','https://loremflickr.com/800/500/fuse','none'),
  ('CM-CINTA-ADHESIVA-001','CM-0012','Cinta adhesiva','Gabinete de repuestos','mejoras_casa','casa','mejoras_casa','[]'::jsonb,null,0,1,'unidad','https://loremflickr.com/800/500/adhesive-tape','none'),
  ('CM-PEGAMENTO-FUERTE-001','CM-0013','Pegamento fuerte','Gabinete de repuestos','mejoras_casa','casa','mejoras_casa','[]'::jsonb,null,0,1,'unidad','https://loremflickr.com/800/500/strong-glue','none'),
  ('CM-ZIP-TIES-001','CM-0014','Amarres plasticos','Gabinete de repuestos','mejoras_casa','casa','mejoras_casa','[]'::jsonb,null,0,1,'paquete','https://loremflickr.com/800/500/zip-ties','none'),
  ('CM-CABLES-REPUESTO-001','CM-0015','Cables de repuesto','Gabinete de repuestos','mejoras_casa','casa','mejoras_casa','[]'::jsonb,null,0,1,'unidad','https://loremflickr.com/800/500/usb-cable','none')
on conflict (id) do nothing;