alter table public.inventory_items
  add column if not exists container_type text,
  add column if not exists parent_container_name text,
  add column if not exists sistema_logico boolean not null default false;

insert into public.inventory_items (
  id,
  alias,
  nombre,
  ubicacion,
  categoria,
  categoria_principal,
  subcategoria,
  contenido,
  notas,
  cantidad_actual,
  cantidad_minima,
  unidad,
  thumbnail_url,
  container_type,
  parent_container_name,
  sistema_logico,
  nfc_mode,
  nfc_target_type,
  nfc_target_path,
  zone_key,
  expiration_enabled,
  expiration_dates,
  updated_at
)
values
  (
    'GB-GP-BOX-MISC-001',
    'GB-0001',
    'Caja Miscelaneo',
    'Gabinete Total - Gavetero Principal',
    'gabinete',
    'gabinete',
    'gavetero_principal',
    '["Equipos para reparar","Bulto con 2 laptops para reparar","Bulto con 2 a 3 telefonos para reparar","Bulto con 4 tablets para reparar (3 iPads Apple y 1 Kindle Fire)","Tornillos varios","Arandelas","Piezas sobrantes de articulos anteriores","Bolsa con cables variados","Cartas de pareja de 7 anos","CD de recuerdos de primer grado 2007","Frame para radio touch de carro","Kit para hacer pulseras"]'::jsonb,
    'Contenedor tematico de backlog y recuerdos.',
    null,
    null,
    null,
    null,
    'thematic_box',
    'Gavetero Principal',
    false,
    'none',
    null,
    null,
    null,
    false,
    '[]'::jsonb,
    now()
  ),
  (
    'GB-GP-BOX-COLECCION-001',
    'GB-0002',
    'Caja Coleccion y Proyectos Creativos',
    'Gabinete Total - Gavetero Principal',
    'gabinete',
    'gabinete',
    'gavetero_principal',
    '["Varias cajas decorativas de productos anteriores","Cartas coleccionables","2 teclados decorativos","Panel PVC con botones arcade funcionales sin joystick","Frame de PVC para pantalla de 7 pulgadas","Proyecto robotico: carrito con 4 ruedas","Proyecto robotico: 4 motores DC","Proyecto robotico: servo","Proyecto robotico: cablerias","Voice Kit para Raspberry Pi con HAT de voz y bocina","Tripode de camara","Audifonos Beats Solo primeras generaciones","Microfono Blue Snowball blanco","Final Fantasy PS1 con case y 4 discos","Album de fotos de pareja","Regalo/foto de San Valentin"]'::jsonb,
    'Contenedor creativo y coleccionable.',
    null,
    null,
    null,
    null,
    'thematic_box',
    'Gavetero Principal',
    false,
    'none',
    null,
    null,
    null,
    false,
    '[]'::jsonb,
    now()
  ),
  (
    'GB-GP-TELA-METALICA-001',
    'GB-0003',
    'Rollos de tela metalica',
    'Gabinete Total - Gavetero Principal',
    'gabinete',
    'gabinete',
    'gavetero_principal',
    '[]'::jsonb,
    null,
    1,
    null,
    'unidad',
    null,
    'direct_item',
    null,
    false,
    'none',
    null,
    null,
    null,
    false,
    '[]'::jsonb,
    now()
  ),
  (
    'GB-GP-WRAP-STRETCH-001',
    'GB-0004',
    'Papel wrap/stretch para embalar',
    'Gabinete Total - Gavetero Principal',
    'gabinete',
    'gabinete',
    'gavetero_principal',
    '[]'::jsonb,
    null,
    1,
    null,
    'rollo',
    null,
    'direct_item',
    null,
    false,
    'none',
    null,
    null,
    null,
    false,
    '[]'::jsonb,
    now()
  ),
  (
    'GB-GP-STAND-PIANO-001',
    'GB-0005',
    'Stand de piano',
    'Gabinete Total - Gavetero Principal',
    'gabinete',
    'gabinete',
    'gavetero_principal',
    '[]'::jsonb,
    null,
    1,
    null,
    'unidad',
    null,
    'direct_item',
    null,
    false,
    'none',
    null,
    null,
    null,
    false,
    '[]'::jsonb,
    now()
  ),
  (
    'GB-GP-SILLA-PIANO-001',
    'GB-0006',
    'Silla de piano',
    'Gabinete Total - Gavetero Principal',
    'gabinete',
    'gabinete',
    'gavetero_principal',
    '[]'::jsonb,
    null,
    1,
    null,
    'unidad',
    null,
    'direct_item',
    null,
    false,
    'none',
    null,
    null,
    null,
    false,
    '[]'::jsonb,
    now()
  ),
  (
    'GB-GP-TUBO-EXTENSOR-001',
    'GB-0007',
    'Tubo extensor ajustable',
    'Gabinete Total - Gavetero Principal',
    'gabinete',
    'gabinete',
    'gavetero_principal',
    '[]'::jsonb,
    null,
    1,
    null,
    'unidad',
    null,
    'direct_item',
    null,
    false,
    'none',
    null,
    null,
    null,
    false,
    '[]'::jsonb,
    now()
  ),
  (
    'GB-GP-VINIL-REFLECTIVO-001',
    'GB-0008',
    'Rollo de vinil reflectivo para cristal',
    'Gabinete Total - Gavetero Principal',
    'gabinete',
    'gabinete',
    'gavetero_principal',
    '[]'::jsonb,
    null,
    1,
    null,
    'rollo',
    null,
    'direct_item',
    null,
    false,
    'none',
    null,
    null,
    null,
    false,
    '[]'::jsonb,
    now()
  ),
  (
    'GB-G1-KIT-RYOBI-90-001',
    'GB-0009',
    'Kit Ryobi drilling and driving 90 piezas',
    'Modulo de Gaveteros - Gavetero 1',
    'gabinete',
    'gabinete',
    'gavetero_1',
    '[]'::jsonb,
    'Gavetero 1 completado.',
    1,
    null,
    'kit',
    null,
    'direct_item',
    null,
    false,
    'none',
    null,
    null,
    null,
    false,
    '[]'::jsonb,
    now()
  ),
  (
    'GB-G1-LAPICES-CONSTRUCCION-001',
    'GB-0010',
    'Lapices de construccion',
    'Modulo de Gaveteros - Gavetero 1',
    'gabinete',
    'gabinete',
    'gavetero_1',
    '[]'::jsonb,
    null,
    7,
    null,
    'unidad',
    null,
    'direct_item',
    null,
    false,
    'none',
    null,
    null,
    null,
    false,
    '[]'::jsonb,
    now()
  ),
  (
    'GB-G1-MARTILLO-001',
    'GB-0011',
    'Martillo',
    'Modulo de Gaveteros - Gavetero 1',
    'gabinete',
    'gabinete',
    'gavetero_1',
    '[]'::jsonb,
    null,
    1,
    null,
    'unidad',
    null,
    'direct_item',
    null,
    false,
    'none',
    null,
    null,
    null,
    false,
    '[]'::jsonb,
    now()
  ),
  (
    'GB-G1-KIT-ROUTER-EXT-001',
    'GB-0012',
    'Kit base/extension de control para router',
    'Modulo de Gaveteros - Gavetero 1',
    'gabinete',
    'gabinete',
    'gavetero_1',
    '[]'::jsonb,
    'Sin router actualmente.',
    1,
    null,
    'kit',
    null,
    'direct_item',
    null,
    false,
    'none',
    null,
    null,
    null,
    false,
    '[]'::jsonb,
    now()
  ),
  (
    'GB-G1-BOX-TORNILLERIA-001',
    'GB-0013',
    'Caja organizadora de tornilleria',
    'Modulo de Gaveteros - Gavetero 1',
    'gabinete',
    'gabinete',
    'gavetero_1',
    '["Tornillos Torx de aproximadamente 2 pulgadas","Tornillos Phillips de aproximadamente 1 pulgada","Arandelas","Tornillos gruesos estructurales"]'::jsonb,
    'Sub-contenedor tecnico.',
    null,
    null,
    null,
    null,
    'sub_box',
    'Gavetero 1',
    false,
    'none',
    null,
    null,
    null,
    false,
    '[]'::jsonb,
    now()
  ),
  (
    'GB-G1-BOX-DRYWALL-001',
    'GB-0014',
    'Caja Drywall',
    'Modulo de Gaveteros - Gavetero 1',
    'gabinete',
    'gabinete',
    'gavetero_1',
    '["Caja de 300 tornillos drywall","2 discos para grinder","1 hole punch","2 tijeras para cortar metal/rack","1 herramienta para esquinas/corking con 4 cabezas intercambiables","3 herramientas similares de aluminio","1 destornillador Phillips de punta fija","1 destornillador multi-puntas sin puntas actualmente"]'::jsonb,
    'Sub-contenedor para trabajos de drywall.',
    null,
    null,
    null,
    null,
    'sub_box',
    'Gavetero 1',
    false,
    'none',
    null,
    null,
    null,
    false,
    '[]'::jsonb,
    now()
  ),
  (
    'GB-G2-NIVEL-1PIE-001',
    'GB-0015',
    'Nivel de 1 pie aproximado',
    'Modulo de Gaveteros - Gavetero 2',
    'gabinete',
    'gabinete',
    'gavetero_2',
    '[]'::jsonb,
    'Gavetero 2 en progreso.',
    1,
    null,
    'unidad',
    null,
    'direct_item',
    null,
    false,
    'none',
    null,
    null,
    null,
    false,
    '[]'::jsonb,
    now()
  ),
  (
    'GB-G2-HERRAMIENTA-CONCRETO-001',
    'GB-0016',
    'Herramienta tipo groover/jointer para concreto',
    'Modulo de Gaveteros - Gavetero 2',
    'gabinete',
    'gabinete',
    'gavetero_2',
    '[]'::jsonb,
    'No incluir cargadores Ryobi en esta zona.',
    1,
    null,
    'unidad',
    null,
    'direct_item',
    null,
    false,
    'none',
    null,
    null,
    null,
    false,
    '[]'::jsonb,
    now()
  ),
  (
    'GB-G3-BOX-CABLES-CARGADORES-001',
    'GB-0017',
    'Caja Cables y Cargadores (Tech Kit)',
    'Modulo de Gaveteros - Gavetero 3',
    'gabinete',
    'gabinete',
    'gavetero_3',
    '["1 cargador USB-C fast charge de 45W","1 cargador Apple USB-C de 20W","1 cargador USB estandar de viaje","1 cargador USB estandar basico","1 cargador Apple Watch USB con base","1 power bank de 5000 mAh","1 Anker PowerCore 26800 A1277","7 cables USB-C genericos","7 cables Micro-USB genericos","3 cables USB-A a USB-B de impresora","1 cable USB-C a USB-A alta velocidad","1 cable USB-C a USB-C modular","1 cable USB-C a Lightning","1 cable Mini-USB tipo control PS3","1 adaptador USB-C macho a USB-A hembra","1 cargador Nintendo DS","Varios videojuegos Nintendo DS","Varios videojuegos Game Boy","1 mouse Corsair","1 mouse generico","1 hub USB 3.1 de 6 puertos con lector SD/TF"]'::jsonb,
    'Contenedor tech kit.',
    null,
    null,
    null,
    null,
    'thematic_box',
    'Gavetero 3',
    false,
    'none',
    null,
    null,
    null,
    false,
    '[]'::jsonb,
    now()
  ),
  (
    'GB-G3-BOX-MAKER-KIT-001',
    'GB-0018',
    'Caja DIY y Electronica (Maker Kit)',
    'Modulo de Gaveteros - Gavetero 3',
    'gabinete',
    'gabinete',
    'gavetero_3',
    '["Kit de accesorios para servomotores","Modulo/kit con Arduino Mega","Sensor ultrasonico","Sensor de vibracion","Headers/expansiones para Raspberry Pi o Arduino","Adaptador HDMI angular","Cables jumper rojo/negro","Mix de accesorios electronicos","30 tags NFC NTAG","6 tarjetas negras NFC","11 tarjetas doradas NFC","2 localizadores GPS circulares","2 covers para GPS","2 soportes para tablet o telefono","1 SSD de 512 GB","1 joystick arcade para proyectos","1 modulo USB joystick","1 cable USB a 4 pines hembra","1 rollo de cable calibre 18 (15 pies rojo y 15 pies negro)","1 cable negro calibre 12 (aprox 3 pies)","1 extension electrica solo conector hembra (aprox 6 pulgadas)","1 cortador/pelacables","Tubos termocontraibles heat shrink","5 bombillas LED pre-cableadas para proyectos","1 cold wallet Tressor"]'::jsonb,
    'Contenedor maker y electronica.',
    null,
    null,
    null,
    null,
    'thematic_box',
    'Gavetero 3',
    false,
    'none',
    null,
    null,
    null,
    false,
    '[]'::jsonb,
    now()
  ),
  (
    'GB-G3-LCD-5P-001',
    'GB-0019',
    'Pantalla LCD de 5 pulgadas',
    'Modulo de Gaveteros - Gavetero 3',
    'gabinete',
    'gabinete',
    'gavetero_3',
    '[]'::jsonb,
    null,
    1,
    null,
    'unidad',
    null,
    'direct_item',
    null,
    false,
    'none',
    null,
    null,
    null,
    false,
    '[]'::jsonb,
    now()
  ),
  (
    'GB-G3-LCD-10P-001',
    'GB-0020',
    'Pantalla LCD 10 pulgadas touchscreen con bocinas',
    'Modulo de Gaveteros - Gavetero 3',
    'gabinete',
    'gabinete',
    'gavetero_3',
    '[]'::jsonb,
    null,
    1,
    null,
    'unidad',
    null,
    'direct_item',
    null,
    false,
    'none',
    null,
    null,
    null,
    false,
    '[]'::jsonb,
    now()
  ),
  (
    'GB-G3-SERVIDOR-HA-001',
    'GB-0021',
    'Servidor Home Assistant',
    'Modulo de Gaveteros - Gavetero 3',
    'gabinete',
    'gabinete',
    'gavetero_3',
    '["Sistema completo: Raspberry Pi 4 + pantalla de 7 pulgadas + case"]'::jsonb,
    'Modelado como sistema logico unico.',
    1,
    null,
    'sistema',
    null,
    'direct_item',
    null,
    true,
    'none',
    null,
    null,
    null,
    false,
    '[]'::jsonb,
    now()
  ),
  (
    'GB-G3-RPI-ZERO2W-001',
    'GB-0022',
    'Raspberry Pi Zero 2 W',
    'Modulo de Gaveteros - Gavetero 3',
    'gabinete',
    'gabinete',
    'gavetero_3',
    '[]'::jsonb,
    null,
    1,
    null,
    'unidad',
    null,
    'direct_item',
    null,
    false,
    'none',
    null,
    null,
    null,
    false,
    '[]'::jsonb,
    now()
  ),
  (
    'GB-G3-BATERIA-LAPTOP-HP-001',
    'GB-0023',
    'Bateria de laptop HP',
    'Modulo de Gaveteros - Gavetero 3',
    'gabinete',
    'gabinete',
    'gavetero_3',
    '[]'::jsonb,
    null,
    1,
    null,
    'unidad',
    null,
    'direct_item',
    null,
    false,
    'none',
    null,
    null,
    null,
    false,
    '[]'::jsonb,
    now()
  ),
  (
    'GB-G3-BATERIA-AGM-001',
    'GB-0024',
    'Bateria AGM sellada AB1250 12V 5Ah',
    'Modulo de Gaveteros - Gavetero 3',
    'gabinete',
    'gabinete',
    'gavetero_3',
    '[]'::jsonb,
    null,
    1,
    null,
    'unidad',
    null,
    'direct_item',
    null,
    false,
    'none',
    null,
    null,
    null,
    false,
    '[]'::jsonb,
    now()
  ),
  (
    'GB-G3-CARGADOR-18650-001',
    'GB-0025',
    'Cargador universal dual slot con 2 baterias 18650',
    'Modulo de Gaveteros - Gavetero 3',
    'gabinete',
    'gabinete',
    'gavetero_3',
    '[]'::jsonb,
    null,
    1,
    null,
    'kit',
    null,
    'direct_item',
    null,
    false,
    'none',
    null,
    null,
    null,
    false,
    '[]'::jsonb,
    now()
  ),
  (
    'GB-G3-TAPE-ELECTRICO-PVC-001',
    'GB-0026',
    'PVC Electrical Tape',
    'Modulo de Gaveteros - Gavetero 3',
    'gabinete',
    'gabinete',
    'gavetero_3',
    '[]'::jsonb,
    null,
    1,
    null,
    'rollo',
    null,
    'direct_item',
    null,
    false,
    'none',
    null,
    null,
    null,
    false,
    '[]'::jsonb,
    now()
  ),
  (
    'GB-G3-CARGADOR-RYOBI-001',
    'GB-0027',
    'Cargadores de baterias Ryobi',
    'Modulo de Gaveteros - Gavetero 3',
    'gabinete',
    'gabinete',
    'gavetero_3',
    '[]'::jsonb,
    'Movidos desde Gavetero 2.',
    2,
    null,
    'unidad',
    null,
    'direct_item',
    null,
    false,
    'none',
    null,
    null,
    null,
    false,
    '[]'::jsonb,
    now()
  ),
  (
    'GB-G3-LED-BAR-RGB-001',
    'GB-0028',
    'LED Light Bars RGB decorativas',
    'Modulo de Gaveteros - Gavetero 3',
    'gabinete',
    'gabinete',
    'gavetero_3',
    '[]'::jsonb,
    null,
    2,
    null,
    'unidad',
    null,
    'direct_item',
    null,
    false,
    'none',
    null,
    null,
    null,
    false,
    '[]'::jsonb,
    now()
  )
on conflict (id) do update set
  alias = excluded.alias,
  nombre = excluded.nombre,
  ubicacion = excluded.ubicacion,
  categoria = excluded.categoria,
  categoria_principal = excluded.categoria_principal,
  subcategoria = excluded.subcategoria,
  contenido = excluded.contenido,
  notas = excluded.notas,
  cantidad_actual = excluded.cantidad_actual,
  cantidad_minima = excluded.cantidad_minima,
  unidad = excluded.unidad,
  thumbnail_url = excluded.thumbnail_url,
  container_type = excluded.container_type,
  parent_container_name = excluded.parent_container_name,
  sistema_logico = excluded.sistema_logico,
  nfc_mode = excluded.nfc_mode,
  nfc_target_type = excluded.nfc_target_type,
  nfc_target_path = excluded.nfc_target_path,
  zone_key = excluded.zone_key,
  expiration_enabled = excluded.expiration_enabled,
  expiration_dates = excluded.expiration_dates,
  updated_at = now();
