insert into public.inventory_items (
  id, alias, nombre, ubicacion, categoria, categoria_principal, subcategoria,
  contenido, notas, cantidad_actual, cantidad_minima, unidad, thumbnail_url,
  container_type, parent_container_name, sistema_logico,
  nfc_mode, nfc_target_type, nfc_target_path, zone_key,
  expiration_enabled, expiration_dates, updated_at
)
values
  (
    'GB-G2-BOX-PRECISION-001',
    'GB-0029',
    'Herramientas de Precision',
    'Modulo de Gaveteros - Gavetero 2',
    'gabinete',
    'gabinete',
    'gavetero_2',
    '["Regla Angular (cortes de 90 grados)","Prensa de 90 grados (uniones rectas)"]'::jsonb,
    'Sub-contenedor para herramientas de precision del Gavetero 2.',
    null,
    null,
    null,
    'https://source.unsplash.com/1200x800/?precision-tools',
    'sub_box',
    'Gavetero 2',
    false,
    'none',
    null,
    null,
    null,
    false,
    '[]'::jsonb,
    now()
  ),
  (
    'GB-G2-REGLA-ANGULAR-001',
    'GB-0030',
    'Regla Angular',
    'Modulo de Gaveteros - Gavetero 2',
    'gabinete',
    'gabinete',
    'gavetero_2',
    '[]'::jsonb,
    'Uso: cortes de 90 grados.',
    1,
    1,
    'unidad',
    'https://source.unsplash.com/1200x800/?angle-ruler',
    'direct_item',
    'Herramientas de Precision',
    false,
    'none',
    null,
    null,
    null,
    false,
    '[]'::jsonb,
    now()
  ),
  (
    'GB-G2-PRENSA-90-001',
    'GB-0031',
    'Prensa de 90 grados',
    'Modulo de Gaveteros - Gavetero 2',
    'gabinete',
    'gabinete',
    'gavetero_2',
    '[]'::jsonb,
    'Uso: uniones rectas.',
    1,
    1,
    'unidad',
    'https://source.unsplash.com/1200x800/?corner-clamp',
    'direct_item',
    'Herramientas de Precision',
    false,
    'none',
    null,
    null,
    null,
    false,
    '[]'::jsonb,
    now()
  ),
  (
    'GB-GP-BOX-HERR-ELECT-CUEVA-001',
    'GB-0032',
    'Herramientas Electricas Cueva',
    'Cueva',
    'gabinete',
    'gabinete',
    'gavetero_principal',
    '["Taladro de Impacto Ryobi","Taladro Ryobi (modo martillo)","Sierra Angular","Router Ryobi","Track Saw (guia de corte recto)"]'::jsonb,
    'Contenedor logico para herramientas electricas de uso externo al gavetero.',
    null,
    null,
    null,
    'https://source.unsplash.com/1200x800/?power-tools',
    'thematic_box',
    'Gavetero Principal',
    false,
    'none',
    null,
    null,
    null,
    false,
    '[]'::jsonb,
    now()
  ),
  (
    'GB-CV-TALADRO-IMPACTO-RYOBI-001',
    'GB-0033',
    'Taladro de Impacto Ryobi',
    'Cueva',
    'gabinete',
    'gabinete',
    'gavetero_principal',
    '[]'::jsonb,
    'Uso: atornillar.',
    1,
    1,
    'unidad',
    'https://source.unsplash.com/1200x800/?impact-driver',
    'direct_item',
    'Herramientas Electricas Cueva',
    false,
    'none',
    null,
    null,
    null,
    false,
    '[]'::jsonb,
    now()
  ),
  (
    'GB-CV-TALADRO-MARTILLO-RYOBI-001',
    'GB-0034',
    'Taladro Ryobi (modo martillo)',
    'Cueva',
    'gabinete',
    'gabinete',
    'gavetero_principal',
    '[]'::jsonb,
    'Uso: perforar paredes y concreto.',
    1,
    1,
    'unidad',
    'https://source.unsplash.com/1200x800/?hammer-drill',
    'direct_item',
    'Herramientas Electricas Cueva',
    false,
    'none',
    null,
    null,
    null,
    false,
    '[]'::jsonb,
    now()
  ),
  (
    'GB-CV-SIERRA-ANGULAR-001',
    'GB-0035',
    'Sierra Angular',
    'Cueva',
    'gabinete',
    'gabinete',
    'gavetero_principal',
    '[]'::jsonb,
    'Uso: cortes angulares.',
    1,
    1,
    'unidad',
    'https://source.unsplash.com/1200x800/?miter-saw',
    'direct_item',
    'Herramientas Electricas Cueva',
    false,
    'none',
    null,
    null,
    null,
    false,
    '[]'::jsonb,
    now()
  ),
  (
    'GB-CV-ROUTER-RYOBI-001',
    'GB-0036',
    'Router Ryobi',
    'Cueva',
    'gabinete',
    'gabinete',
    'gavetero_principal',
    '[]'::jsonb,
    'Uso: cortes de precision en madera.',
    1,
    1,
    'unidad',
    'https://source.unsplash.com/1200x800/?wood-router',
    'direct_item',
    'Herramientas Electricas Cueva',
    false,
    'none',
    null,
    null,
    null,
    false,
    '[]'::jsonb,
    now()
  ),
  (
    'GB-CV-TRACK-SAW-001',
    'GB-0037',
    'Track Saw (Guia de corte recto)',
    'Cueva',
    'gabinete',
    'gabinete',
    'gavetero_principal',
    '[]'::jsonb,
    'Capacidad aproximada: 4 a 5 pies.',
    1,
    1,
    'unidad',
    'https://source.unsplash.com/1200x800/?track-saw',
    'direct_item',
    'Herramientas Electricas Cueva',
    false,
    'none',
    null,
    null,
    null,
    false,
    '[]'::jsonb,
    now()
  ),
  (
    'GB-CV-SYS-RYOBI-18V-001',
    'GB-0038',
    'Sistema Ryobi 18V',
    'Cueva',
    'gabinete',
    'gabinete',
    'gavetero_principal',
    '["Bateria Ryobi 1.5Ah","Bateria Ryobi 2Ah","Bateria Ryobi 4Ah"]'::jsonb,
    'Grupo logico del ecosistema de baterias Ryobi.',
    null,
    null,
    null,
    'https://source.unsplash.com/1200x800/?tool-batteries',
    'system_group',
    'Gavetero Principal',
    true,
    'none',
    null,
    null,
    null,
    false,
    '[]'::jsonb,
    now()
  ),
  (
    'GB-CV-BATERIA-RYOBI-15AH-001',
    'GB-0039',
    'Bateria Ryobi 1.5Ah',
    'Cueva',
    'gabinete',
    'gabinete',
    'gavetero_principal',
    '[]'::jsonb,
    null,
    1,
    1,
    'unidad',
    'https://source.unsplash.com/1200x800/?rechargeable-battery-pack',
    'direct_item',
    'Sistema Ryobi 18V',
    true,
    'none',
    null,
    null,
    null,
    false,
    '[]'::jsonb,
    now()
  ),
  (
    'GB-CV-BATERIA-RYOBI-2AH-001',
    'GB-0040',
    'Bateria Ryobi 2Ah',
    'Cueva',
    'gabinete',
    'gabinete',
    'gavetero_principal',
    '[]'::jsonb,
    null,
    1,
    1,
    'unidad',
    'https://source.unsplash.com/1200x800/?power-tool-battery',
    'direct_item',
    'Sistema Ryobi 18V',
    true,
    'none',
    null,
    null,
    null,
    false,
    '[]'::jsonb,
    now()
  ),
  (
    'GB-CV-BATERIA-RYOBI-4AH-001',
    'GB-0041',
    'Bateria Ryobi 4Ah',
    'Cueva',
    'gabinete',
    'gabinete',
    'gavetero_principal',
    '[]'::jsonb,
    null,
    1,
    1,
    'unidad',
    'https://source.unsplash.com/1200x800/?battery-tool',
    'direct_item',
    'Sistema Ryobi 18V',
    true,
    'none',
    null,
    null,
    null,
    false,
    '[]'::jsonb,
    now()
  )

on conflict (id) do update set
  alias = excluded.alias,
  nombre = excluded.nombre,
  ubicacion = excluded.ubicacion,
  categoria = excluded.categoria,
  categoria_principal = excluded.categoria_principal,
  subcategoria = excluded.subcategoria,
  contenido = excluded.contenido,
  notas = excluded.notas,
  cantidad_actual = excluded.cantidad_actual,
  cantidad_minima = excluded.cantidad_minima,
  unidad = excluded.unidad,
  thumbnail_url = excluded.thumbnail_url,
  container_type = excluded.container_type,
  parent_container_name = excluded.parent_container_name,
  sistema_logico = excluded.sistema_logico,
  nfc_mode = excluded.nfc_mode,
  nfc_target_type = excluded.nfc_target_type,
  nfc_target_path = excluded.nfc_target_path,
  zone_key = excluded.zone_key,
  expiration_enabled = excluded.expiration_enabled,
  expiration_dates = excluded.expiration_dates,
  updated_at = now();
